packages:
  - packages/*
publicHoistPattern:
  - "react-native*"
  - "@react-native*"
allowBuilds:
  esbuild: false
catalog:
  "@oxfmt/binding-darwin-arm64": "^0.58.0"
  "@oxfmt/binding-win32-x64-msvc": "^0.58.0"
  "@oxlint/binding-darwin-arm64": "^1.73.0"
  "@oxlint/binding-win32-x64-msvc": "^1.73.0"
  "npm-run-all2": "^9.0.2"
  "oxfmt": "^0.58.0"
  "oxlint": "^1.73.0"
  "tsdown": "^0.22.5"
  "typescript": "^7.0.2"
